-- ==========================================================
-- Banking Application - Database Schema & Seed Data
-- Compatible with PostgreSQL 15+
-- ==========================================================

-- Drop existing tables if re-initializing (Optional, commented out by default)
-- DROP TABLE IF EXISTS transactions CASCADE;
-- DROP TABLE IF EXISTS accounts CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Accounts Table
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL UNIQUE,
    account_type VARCHAR(20) NOT NULL,
    balance NUMERIC(19, 4) NOT NULL DEFAULT 0.0000,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_account_balance_non_negative CHECK (balance >= 0)
);

CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON accounts (user_id);
CREATE INDEX IF NOT EXISTS idx_accounts_account_number ON accounts (account_number);

-- 3. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference VARCHAR(64) NOT NULL UNIQUE,
    source_account_id BIGINT,
    target_account_id BIGINT,
    amount NUMERIC(19, 4) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    description VARCHAR(255),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_source FOREIGN KEY (source_account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_target FOREIGN KEY (target_account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT chk_transaction_amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_transactions_source_account_id ON transactions (source_account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_target_account_id ON transactions (target_account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_timestamp ON transactions (timestamp DESC);

-- ==========================================================
-- 4. Initial Seed Data
-- ==========================================================

-- Insert Initial Users
INSERT INTO users (id, username, email, password_hash, full_name, created_at, updated_at)
VALUES
    (1, 'johndoe', 'john@example.com', 'Password123', 'John Doe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'janesmith', 'jane@example.com', 'Password123', 'Jane Smith', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- Insert Initial Accounts
INSERT INTO accounts (id, account_number, account_type, balance, currency, status, user_id, created_at, updated_at)
VALUES
    (1, '1234567890', 'SAVINGS', 1500.0000, 'USD', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, '9876543210', 'CHECKING', 3200.5000, 'USD', 'ACTIVE', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, '5555666677', 'CHECKING', 850.0000, 'USD', 'ACTIVE', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- Insert Initial Transactions
INSERT INTO transactions (id, transaction_reference, source_account_id, target_account_id, amount, transaction_type, status, description, timestamp)
VALUES
    (1, 'TXN-INIT-001', NULL, 1, 1000.0000, 'DEPOSIT', 'SUCCESS', 'Initial savings deposit', CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (2, 'TXN-INIT-002', NULL, 2, 3200.5000, 'DEPOSIT', 'SUCCESS', 'Opening balance deposit', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (3, 'TXN-INIT-003', NULL, 1, 500.0000, 'DEPOSIT', 'SUCCESS', 'Payroll direct deposit', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- Synchronize Identity Sequences
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('accounts', 'id'), COALESCE((SELECT MAX(id) FROM accounts), 1), true);
SELECT setval(pg_get_serial_sequence('transactions', 'id'), COALESCE((SELECT MAX(id) FROM transactions), 1), true);
